# Generated by Django 4.1.5 on 2023-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=300)),
                ('address', models.IntegerField()),
                ('postalCode', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
