# Generated by Django 4.1.5 on 2023-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('unitPrice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discountAvailable', models.BooleanField(default=False)),
            ],
        ),
    ]
